export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const AUTHENTICATE_USERS_REQUEST = 'AUTHENTICATE_USERS_REQUEST';
export const AUTHENTICATE_USERS_SUCCESS = 'AUTHENTICATE_USERS_SUCCESS';
export const AUTHENTICATE_USERS_ERROR = 'AUTHENTICATE_USERS_ERROR';

export const CLEAR_TOAST_MESSAGE = 'CLEAR_TOAST_MESSAGE';
